#!/usr/bin/env node
/**
 * One-stop-shop for the money / soul-stack.
 *
 * The single command Ben runs before any "share with Nic" or "talk to a
 * funder" moment to know the state of everything in one terminal page.
 *
 * Wraps:
 *   1. scripts/four-lanes-snapshot.mjs            (refresh the cockpit MD)
 *   2. scripts/check-money-stack-alignment.mjs    (drift detection, repo-side)
 *   3. scripts/audit-notion-money-stack.mjs --money-only  (Notion-side audit, if NOTION_TOKEN works)
 *
 * Aggregates the outputs into a single overview at
 *   wiki/cockpit/money-status-YYYY-MM-DD.md
 * and prints a tight terminal summary.
 *
 * Usage:
 *   node scripts/money-status.mjs              # full run
 *   node scripts/money-status.mjs --skip-audit # skip Notion audit (fast path)
 *   node scripts/money-status.mjs --quiet      # one-screen terminal summary, no full output
 *
 * Plan: wiki/decisions/money-stack-one-stop-shop.md
 */
import { execSync } from 'node:child_process'
import { readFileSync, existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const REPO_ROOT = join(__dirname, '..')

const argv = process.argv.slice(2)
const SKIP_AUDIT = argv.includes('--skip-audit')
const QUIET = argv.includes('--quiet')

const TODAY = new Date().toISOString().slice(0, 10)
const COCKPIT_DIR = join(REPO_ROOT, 'wiki/cockpit')
const FOUR_LANES_PATH = join(COCKPIT_DIR, 'four-lanes-today.md')
const ALIGNMENT_PATH = join(COCKPIT_DIR, `money-stack-alignment-${TODAY}.md`)
const AUDIT_PATH = join(COCKPIT_DIR, `notion-money-stack-audit-${TODAY}.md`)
const STATUS_PATH = join(COCKPIT_DIR, `money-status-${TODAY}.md`)

const log = (m) => console.log(`[money-status] ${m}`)

function runQuiet(cmd) {
  try {
    return { ok: true, out: execSync(cmd, { cwd: REPO_ROOT, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] }) }
  } catch (e) {
    return { ok: false, out: (e.stdout || '') + (e.stderr || ''), err: e.message }
  }
}

function safeRead(p) {
  return existsSync(p) ? readFileSync(p, 'utf-8') : null
}

function extractStatusLine(md) {
  if (!md) return null
  const m = md.match(/^Status:\s*(.+)$/m)
  return m ? m[1].trim() : null
}

function extractFourLanesHeadline(md) {
  if (!md) return null
  const seg = md.match(/## Last 90 days\n\n([\s\S]+?)(?:\n##|$)/)
  if (!seg) return null
  // Convert "- **To Us**: $0 (0%)" lines into "To Us $0 (0%)" then join.
  return seg[1]
    .trim()
    .split('\n')
    .filter((l) => l.trim().startsWith('-'))
    .map((l) => l.replace(/^-\s*/, '').replace(/\*\*/g, '').replace(/:\s*/, ' '))
    .join(' · ')
}

function extractAuditCounts(md) {
  if (!md) return null
  const m = md.match(/^Buckets:\s*(.+)$/m)
  return m ? m[1].trim() : null
}

async function main() {
  const startedAt = new Date()
  log(`starting one-stop-shop refresh at ${startedAt.toISOString()}`)

  // 1. Four-lanes snapshot — always cheap
  log('refreshing four-lanes snapshot')
  const snap = runQuiet(`node ${join(__dirname, 'four-lanes-snapshot.mjs')}`)
  if (!snap.ok) log(`WARN: four-lanes-snapshot failed: ${snap.err}`)

  // 2. Alignment check — always cheap
  log('running alignment check')
  const align = runQuiet(`node ${join(__dirname, 'check-money-stack-alignment.mjs')}`)
  if (!align.ok) log(`WARN: alignment-check failed: ${align.err}`)

  // 3. Notion audit — slow + needs working token
  let auditStatus = 'skipped'
  if (!SKIP_AUDIT && process.env.NOTION_TOKEN) {
    log('running notion audit (this may take ~30s)')
    const audit = runQuiet(`node ${join(__dirname, 'audit-notion-money-stack.mjs')} --money-only`)
    auditStatus = audit.ok ? 'ok' : 'failed'
    if (!audit.ok) log(`WARN: notion-audit failed: ${audit.err}`)
  } else if (SKIP_AUDIT) {
    auditStatus = 'skipped (--skip-audit)'
  } else {
    auditStatus = 'skipped (NOTION_TOKEN not set)'
  }

  // Aggregate
  const lanes = safeRead(FOUR_LANES_PATH)
  const alignmentMd = safeRead(ALIGNMENT_PATH)
  const auditMd = auditStatus === 'ok' ? safeRead(AUDIT_PATH) : null

  const headlines = {
    four_lanes_90d: extractFourLanesHeadline(lanes) || '(snapshot missing)',
    alignment_status: extractStatusLine(alignmentMd) || '(check missing)',
    audit_buckets: extractAuditCounts(auditMd) || `(audit ${auditStatus})`,
  }

  // Build one-stop-shop markdown
  const lines = []
  lines.push(`# Money status — ${TODAY}`, '')
  lines.push(`> Generated by \`scripts/money-status.mjs\` at ${startedAt.toISOString()}.`, '')
  lines.push(`## At a glance`, '')
  lines.push(`- **Four lanes (last 90d)**: ${headlines.four_lanes_90d}`)
  lines.push(`- **Alignment**: ${headlines.alignment_status}`)
  lines.push(`- **Notion audit**: ${headlines.audit_buckets}`)
  lines.push('')
  lines.push(`## Components`, '')
  lines.push(`- Four-lanes snapshot: \`${FOUR_LANES_PATH.replace(REPO_ROOT + '/', '')}\``)
  lines.push(`- Alignment check: \`${ALIGNMENT_PATH.replace(REPO_ROOT + '/', '')}\``)
  if (auditStatus === 'ok') {
    lines.push(`- Notion audit: \`${AUDIT_PATH.replace(REPO_ROOT + '/', '')}\``)
  } else {
    lines.push(`- Notion audit: ${auditStatus}`)
  }
  lines.push('')
  if (alignmentMd) {
    lines.push(`---`, '', `## Alignment-check detail`, '')
    lines.push(alignmentMd.replace(/^# Money-stack alignment check.*?\n\n/, ''))
  }

  writeFileSync(STATUS_PATH, lines.join('\n'))
  log(`wrote ${STATUS_PATH}`)

  // Mirror to Notion (fail-soft: skips quietly if NOTION_TOKEN dead or
  // cfg.moneyStatus unset).
  runQuiet(`node ${join(__dirname, 'sync-money-status-to-notion.mjs')}`)

  // Terminal summary
  if (!QUIET) {
    console.log('')
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log(`  Money status — ${TODAY}`)
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log(`  Four lanes (90d):  ${headlines.four_lanes_90d}`)
    console.log(`  Alignment:         ${headlines.alignment_status}`)
    console.log(`  Notion audit:      ${headlines.audit_buckets}`)
    console.log('')
    console.log(`  Full report: ${STATUS_PATH.replace(REPO_ROOT + '/', '')}`)
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  } else {
    console.log(`Four lanes 90d: ${headlines.four_lanes_90d}`)
    console.log(`Alignment: ${headlines.alignment_status}`)
    console.log(`Notion audit: ${headlines.audit_buckets}`)
  }
}

main().catch((err) => {
  console.error('[money-status] fatal:', err.stack || err.message)
  process.exit(1)
})
